sudo: required
language: python
cache: pip
git:
  depth: false
  quiet: true

python: # The following versions
  - "3.6"
  - "3.7"
# command to install dependencies

build:
  stage: build
  only:
    - paths:
      - "^codes/*"

install:
  - pip install numpy
  - pip install matplotlib
  - pip install pandas
  - pip install seaborn
  - pip install pathlib
  - pip install tensorflow_datasets
  - pip install scikit-image
  # install TensorFlow from https://storage.googleapis.com/tensorflow/
  - if [[ "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then
      pip install https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow_cpu-2.3.0-cp36-cp36m-manylinux2010_x86_64.whl;
    elif [[ "$TRAVIS_PYTHON_VERSION" == "3.7" ]]; then
      pip install https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow_cpu-2.3.0-cp37-cp37m-manylinux2010_x86_64.whl;
    fi
script:
  # You can run all python files in parallel, http://stackoverflow.com/questions/5015316
  # - find codes/python/ -type f -name "*.py" |xargs -n 1 python
  # get list of changed files and if they are Python files, run them.
  - ./travis.sh
